# Generated by Django 4.2.5 on 2024-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langganan_paket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='jenis_paket',
        ),
        migrations.DeleteModel(
            name='Akun',
        ),
        migrations.DeleteModel(
            name='Paket',
        ),
        migrations.DeleteModel(
            name='Premium',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
